### ISSUE TITLE
Create a process that agregates the Consumer logfile

### ISSUE THREAD

**Issue by sbouchardet** [RegadorAutomaticoConsciente/RACAP#1]
Today the consumer write a logfile named Consumer.log. 
The issue target is to implement a process  that transform the logfile in a file with Prolog facts.

-------
Obs.: There are some questions that we need to answer:
 - This command will run at the same time that the log file is being written ?
 - if, for some reason, this command stops. Will it process the logfile from the beginning?
- will It generates only the kb for the last registered day?

**Comment by dmvieira** [comment]
- I did another process for that
- Yes, running every hour and updating kb
- Yes, backup script will remove Consumer.log every day

**Comment by dmvieira** [comment]
For me, it's ready with this commit: https://github.com/RegadorAutomaticoConsciente/RACAP/commit/51a38dd9e02a84a9e757bab5297e4238cafc6723
